# Generated by Django 4.2.5 on 2023-09-27 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentstatus',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='departmentworkflow',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentworkflow',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='encroachmentdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='encroachmentdepartment',
            name='encroachment',
        ),
        migrations.RemoveField(
            model_name='encroachmentdepartment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='encroachmentdepartment',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='encroachment',
            name='departments',
        ),
        migrations.AddField(
            model_name='encroachment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enchroachAPP.department'),
        ),
        migrations.AddField(
            model_name='encroachment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enchroachAPP.encroachmentstatus'),
        ),
        migrations.DeleteModel(
            name='DepartmentStage',
        ),
        migrations.DeleteModel(
            name='DepartmentStatus',
        ),
        migrations.DeleteModel(
            name='DepartmentWorkflow',
        ),
        migrations.DeleteModel(
            name='EncroachmentDepartment',
        ),
        migrations.DeleteModel(
            name='EncroachmentWorkflow',
        ),
    ]
