# Generated by Django 4.2.5 on 2023-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0002_remove_departmentstatus_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='encroachmentstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encroachmentstatus',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
