# Generated by Django 4.2.5 on 2023-09-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0003_remove_department_id_remove_encroachmentstatus_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('subregion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='encroachment',
            name='region',
        ),
        migrations.RemoveField(
            model_name='encroachment',
            name='subregion',
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='criticality',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='department',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='encroachment_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EncroachmentStatus',
        ),
        migrations.AddField(
            model_name='encroachment',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enchroachAPP.area'),
        ),
    ]
