# Generated by Django 4.2.5 on 2023-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0004_area_remove_encroachment_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encroachment',
            name='criticality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
