# Generated by Django 4.2.5 on 2023-09-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0005_alter_encroachment_criticality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encroachment',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchroachAPP.area'),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='encroachment_type',
            field=models.CharField(max_length=255),
        ),
    ]
