# Generated by Django 4.2.5 on 2023-09-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0006_alter_encroachment_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encroachment',
            old_name='department',
            new_name='encroachment_department',
        ),
        migrations.RenameField(
            model_name='encroachment',
            old_name='status',
            new_name='encroachment_status',
        ),
    ]
