# Generated by Django 4.2.5 on 2023-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0007_rename_department_encroachment_encroachment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encroachment',
            name='encroachment_department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='encroachment',
            name='encroachment_status',
            field=models.CharField(max_length=200),
        ),
    ]
