# Generated by Django 4.2.5 on 2023-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0008_alter_encroachment_encroachment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='id',
        ),
        migrations.AlterField(
            model_name='area',
            name='region',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
