# Generated by Django 4.2.5 on 2023-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0009_remove_area_id_alter_area_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encroachment',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, default=('A', 'B'), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='area',
            name='subregion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
