# Generated by Django 4.2.5 on 2023-09-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enchroachAPP', '0011_alter_area_region_alter_area_subregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='encroachment',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enchroachAPP.area'),
            preserve_default=False,
        ),
    ]
